### ISSUE TITLE
Additional matchers

### ISSUE THREAD

**Issue by mohamnag** [FDMediagroep/hamcrest-jsoup#3]
It would be great if there were some other matcher like these also available:

 - hasChild(String cssSelector) ~> check if a child with given selector exists. currently I use `assertThat(doc, selectingFirst(cssSelector, notNullValue(Element.class)))` 

 - hasChild(String cssSelector, int searchDepth) ~> limit search in a specific depth, not sure if this can be done easily currently

 - hasUniqueChild(String cssSelector) ~> check if there is one and only one child with given selector, currently not easy as `selecting` returns a iterable and not a list. even if it was returning a list, again this was a great shortcut.

Currently these are my most wanted list, would add any new if I find. I have equivalents of most of these selectors but having a lengthy assert command is exactly what hamcrest is meant not to be.

**Comment by jmsnoeij** [comment]
Hi!
Thanks for you interest in our little project !

Do you feel comfortable enough to add a merge request for this ??

With kind regards,

Jeroen M Snoeij

**Comment by mohamnag** [comment]
Little but very useful!
I believe so, I will take a look at it next week as the time on weekend is already planned ;)

**Comment by mohamnag** [comment]
as I already suspected `hasChild(String cssSelector, int searchDepth)` matcher was not possible (due to JSOUP limits but the other two are implemented including tests.

**Comment by jmsnoeij** [comment]
new release is available in Sonatype and will pread out to central eventually:
https://oss.sonatype.org/service/local/repositories/releases/content/nl/fd/hamcrest-jsoup/0.1.12/hamcrest-jsoup-0.1.12.jar
