### ISSUE TITLE
Selecting.selecting does not work with Matchers#hasItem(Matcher<? super T>)

### ISSUE THREAD

**Issue by madisparn** [FDMediagroep/hamcrest-jsoup#6]
`assertThat(html, selecting("table", hasItem(hasText(containsString("some test")))));`
Produces compile error with jdk1.8.0_161:
> java: incompatible types: org.hamcrest.Matcher<java.lang.Iterable<? super org.jsoup.nodes.Element>> cannot be converted to org.hamcrest.Matcher<java.lang.Iterable<org.jsoup.nodes.Element>>

**Comment by madisparn** [comment]
Looks to be fixed in master

**Comment by OrangeDog** [comment]
Can you publish the fix for this please.

**Comment by jmsnoeij** [comment]
@OrangeDog I'm sorry to say that we stopped using this library internal some time ago (as the number of recent changes might suspect). We have no plans to release this artifact to central (and we kinda lost the procedure to do so when we dropped Jenkins .... :( ).
For now I would suggest that you simply take the code and install this artifact in your local maven repo and use it when applicable.
